# Generated by Django 5.0.3 on 2025-02-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(max_length=100, null=-1),
            preserve_default=-1,
        ),
    ]
