# Generated by Django 5.0.3 on 2025-05-15 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classes.event')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField(help_text='Duration of the class in minutes.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)])),
            ],
            bases=('classes.event',),
        ),
        migrations.CreateModel(
            name='TeachingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the resource.', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the resource.', max_length=500, null=True)),
                ('file', models.FileField(blank=True, help_text='Upload a file for the resource.', null=True, upload_to='resources/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(help_text='The subject to which this resource belongs.', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('class_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='classes.classevent')),
            ],
        ),
    ]
