# Generated by Django 5.2.5 on 2025-11-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classevent',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_accounts.classgroup'),
        ),
        migrations.AddField(
            model_name='classevent',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='class_events_as_student', to='user_accounts.customuser'),
        ),
        migrations.AddField(
            model_name='classevent',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='classevent',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='class_events_as_teacher', to='user_accounts.customuser'),
        ),
    ]
