# Generated by Django 5.2.5 on 2025-11-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classevent',
            name='access_token',
            field=models.CharField(blank=True, help_text='Secure token for classroom access', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='classevent',
            name='classroom_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled Class'), ('practice', 'Practice/Demo Class')], default='scheduled', help_text='Type of classroom: scheduled or practice', max_length=20),
        ),
        migrations.AddField(
            model_name='classevent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the classroom is currently active'),
        ),
    ]
