# Generated by Django 5.2.5 on 2026-06-03 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_remove_teachingresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classevent',
            name='access_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='classevent',
            name='classroom_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled Class'), ('practice', 'Practice/Demo Class')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='classevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sessionfeedback',
            name='rating',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
