# Generated by Django 5.2.5 on 2026-06-04 09:35

from django.db import migrations


def seed_subject_tags(apps, schema_editor):
    """Migrate each class event's subject into a subject-kind tag before the FK is dropped."""
    ClassEvent = apps.get_model("classes", "ClassEvent")
    Tag = apps.get_model("tags", "Tag")
    TaggedItem = apps.get_model("tags", "TaggedItem")
    ContentType = apps.get_model("contenttypes", "ContentType")

    ct, _ = ContentType.objects.get_or_create(
        app_label="classes", model="classevent"
    )
    for event in ClassEvent.objects.select_related("subject").all():
        subject = event.subject
        if not subject:
            continue
        tag, _ = Tag.objects.get_or_create(
            name=subject.name, kind="subject", defaults={"color": subject.color}
        )
        TaggedItem.objects.get_or_create(
            tag=tag, content_type=ct, object_id=event.id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_classevent_access_token_and_more'),
        ('tags', '0001_initial'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        # Seed tags first (subject column still exists at this point), then drop it.
        migrations.RunPython(seed_subject_tags, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='classevent',
            name='subject',
        ),
    ]
