# Generated by Django 5.0.3 on 2025-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='customaccount',
            name='subjects',
            field=models.ManyToManyField(to='subjects.subject'),
        ),
    ]
