# Generated by Django 5.2.5 on 2025-11-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='color',
            field=models.CharField(choices=[('#1976D2', 'Blue'), ('#388E3C', 'Green'), ('#7B1FA2', 'Purple'), ('#D32F2F', 'Red'), ('#F57C00', 'Orange'), ('#0097A7', 'Cyan'), ('#C2185B', 'Pink'), ('#5D4037', 'Brown'), ('#455A64', 'Blue Grey'), ('#FBC02D', 'Yellow')], default='#1976D2', max_length=7),
        ),
    ]
