# Generated by Django 5.0.3 on 2025-01-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('class_code', models.CharField(max_length=50, unique=True)),
                ('max_students', models.PositiveIntegerField(blank=True, null=True)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('archived', 'Archived')], default='active', max_length=10)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_groups', to='user_accounts.customuser')),
                ('students', models.ManyToManyField(related_name='class_groups', to='user_accounts.student')),
                ('subjects', models.ManyToManyField(related_name='class_groups', to='subjects.subject')),
                ('teachers', models.ManyToManyField(related_name='class_groups', to='user_accounts.teacher')),
            ],
        ),
    ]
