"""
Django settings for lessonbase project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = os.environ.get("ENVIRONMENT") == "development"

BASE_URL = os.environ.get("BASE_URL")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!

HOSTNAME = os.environ.get("HOSTNAME")

# Allow configuring ALLOWED_HOSTS via environment variable (comma-separated)
# Example: ALLOWED_HOSTS=api.teach.jkenny.tech,backend.example.com
env_allowed = os.environ.get("ALLOWED_HOSTS")

if os.environ.get("ENVIRONMENT") == "production":
    # Production hosts - VPS deployment
    ALLOWED_HOSTS = [
        "api.teach.jkenny.tech",
        "teach.jkenny.tech",  # For WebSocket connections from frontend
        ".jkenny.tech",  # Allow all jkenny.tech subdomains
    ]
else:
    # Development mode - keep strict
    ALLOWED_HOSTS = [
        HOSTNAME,
        "localhost",
        "127.0.0.1",
        "0.0.0.0",
    ]

if env_allowed:
    # Merge additional hosts from env (strip whitespace, ignore empties)
    ALLOWED_HOSTS += [h.strip() for h in env_allowed.split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "rest_framework.authtoken",
    "polymorphic",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required by allauth
    "rest_framework",
    "corsheaders",
    "channels",
    "apps.subjects",
    "apps.user_accounts",
    "apps.classes",
    "apps.storage",
    "apps.assignments",
    "apps.core.apps.CoreConfig",
    # Allauth
    "allauth",
    "allauth.account",
    # Optional -- requires install using `django-allauth[socialaccount]`.
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # CORS middleware must come before CommonMiddleware so it can intercept
    # and respond to preflight OPTIONS requests.
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

# Django-allauth configuration (updated for latest version)
ACCOUNT_LOGIN_METHODS = {"email"}  # Use email for authentication
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]  # Required signup fields
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Require email verification
ACCOUNT_CONFIRM_EMAIL_ON_GET = False  # Don't auto-confirm on GET, we'll handle via API
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = (
    None  # No redirect for anonymous users
)
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = None
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False  # Don't auto-login after confirmation
ACCOUNT_ADAPTER = (
    "apps.core.adapters.CustomAccountAdapter"  # Custom adapter for API behavior
)
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"

# Social account settings
SOCIALACCOUNT_ADAPTER = "apps.core.adapters.CustomSocialAccountAdapter"
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"  # Social accounts are already verified
SOCIALACCOUNT_AUTO_SIGNUP = True  # Auto-create account on social login
SOCIALACCOUNT_QUERY_EMAIL = True  # Request email from social providers

# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
            "key": "",
        },
    }
}

# Frontend URL for email redirects
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")

# Production frontend URL
if os.environ.get("ENVIRONMENT") == "production":
    FRONTEND_URL = os.environ.get("FRONTEND_URL", "https://teach.jkenny.tech")

# Site ID (required by allauth)
SITE_ID = 1


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("REDIS_URL", "redis://127.0.0.1:6379")],
        },
    },
}


R2_ACCOUNT_ID = os.environ.get("R2_ACCOUNT_ID")
R2_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY_ID")
R2_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_ACCESS_KEY") or os.environ.get(
    "R2_ACCESS_SECRET"
)
R2_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME", "lessonbase")
R2_ENDPOINT_URL = os.environ.get(
    "R2_ENDPOINT_URL",
    os.environ.get("R2_S3_API")
    or os.environ.get("R2_ENDPOINT")
    or os.environ.get("AWS_S3_ENDPOINT_URL")
    or (f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com" if R2_ACCOUNT_ID else None),
)

AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
AWS_S3_ENDPOINT_URL = R2_ENDPOINT_URL
AWS_S3_REGION_NAME = os.environ.get("R2_REGION", "auto")
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "path"
AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = None

STORAGES = {
    "default": {
        "BACKEND": "apps.storage.storage_backends.R2MediaStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Check if individual POSTGRES_* variables are set (Docker/containerized environments)
if os.environ.get("POSTGRES_DB"):
    # ✅ Docker/containerized environment using individual POSTGRES_* variables
    # This avoids URL encoding issues with special characters in passwords
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB"),
            "USER": os.environ.get("POSTGRES_USER"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
            "HOST": os.environ.get("POSTGRES_HOST", "db"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": 600,
        }
    }
elif os.environ.get("DATABASE_URL"):
    # ✅ Alternative: Using DATABASE_URL (e.g., Heroku, other PaaS)
    # Note: Passwords with special characters must be URL-encoded in DATABASE_URL
    DATABASES = {
        "default": dj_database_url.config(
            default=os.environ.get("DATABASE_URL"),
            conn_max_age=600,
        )
    }
else:
    # ✅ Fallback: Default development configuration
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "mydb",
            "USER": "myuser",
            "PASSWORD": "mypassword",
            "HOST": "localhost",
            "PORT": "5432",
        }
    }

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly",
    ]
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

AUTH_USER_MODEL = "user_accounts.CustomAccount"

# CORS configuration. In production we recommend setting this via an
# environment variable containing a comma-separated list of origins
# (for example: CORS_ALLOWED_ORIGINS=https://teach.jkenny.tech)
default_cors = [
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://localhost:3000",
]

# Production CORS origins for VPS deployment
if os.environ.get("ENVIRONMENT") == "production":
    default_cors = [
        "https://teach.jkenny.tech",
    ]

cors_env = os.environ.get("CORS_ALLOWED_ORIGINS")
if cors_env:
    # Allow passing a comma-separated list in the environment
    CORS_ALLOWED_ORIGINS = [o.strip() for o in cors_env.split(",") if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = default_cors

# Additional CORS settings for authentication
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# CSRF Trusted Origins for secure connections
# Required for WebSocket connections over WSS
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")  # Your email address
EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD"
)  # Use environment variable for security
