# Generated by Django 5.0.3 on 2025-05-15 15:04

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the assignment.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the assignment.', max_length=1000, null=True)),
                ('max_score', models.PositiveIntegerField(help_text='Maximum score that can be achieved for this assignment.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_date', models.DateField(default=django.utils.timezone.now, help_text='The date when the homework was assigned.')),
                ('due_date', models.DateField(help_text='The deadline for the homework.')),
                ('to_mark', models.BooleanField(default=False)),
                ('marked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('answer_text', models.TextField(blank=True, help_text="Student's written response.")),
                ('graded', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text="Teacher's feedback text.", max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
