# Generated by Django 5.2.5 on 2025-11-03 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='class_groups',
            field=models.ManyToManyField(related_name='assignment_as_class_group', to='user_accounts.classgroup'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='material',
            field=models.ManyToManyField(related_name='homework_resource', to='classes.teachingresource'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(help_text='Students assigned to this work.', related_name='assignments_as_student', to='user_accounts.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(help_text='The subject to which this assignment belongs.', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teachers',
            field=models.ManyToManyField(help_text='Teachers assigning this work.', related_name='assignments_as_teacher', to='user_accounts.customuser'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_attempts', to='user_accounts.student'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='submitted_files',
            field=models.ManyToManyField(blank=True, related_name='assignment_attempts', to='classes.teachingresource'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='assignmentAttempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='assignments.assignmentattempt'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_files',
            field=models.ManyToManyField(blank=True, related_name='feedbacks', to='classes.teachingresource'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.customuser'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentattempt',
            unique_together={('assignment', 'student')},
        ),
    ]
