# Generated by Django 5.0.3 on 2025-06-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='submitted_files',
            field=models.ManyToManyField(blank=True, related_name='feedbacks', to='classes.teachingresource'),
        ),
    ]
