# Generated by Django 5.2.5 on 2026-06-04 09:35

from django.db import migrations


def seed_subject_tags(apps, schema_editor):
    """Migrate each assignment's subject into a subject-kind tag before the FK is dropped."""
    Assignment = apps.get_model("assignments", "Assignment")
    Tag = apps.get_model("tags", "Tag")
    TaggedItem = apps.get_model("tags", "TaggedItem")
    ContentType = apps.get_model("contenttypes", "ContentType")

    ct, _ = ContentType.objects.get_or_create(
        app_label="assignments", model="assignment"
    )
    for assignment in Assignment.objects.select_related("subject").all():
        subject = assignment.subject
        if not subject:
            continue
        tag, _ = Tag.objects.get_or_create(
            name=subject.name, kind="subject", defaults={"color": subject.color}
        )
        TaggedItem.objects.get_or_create(
            tag=tag, content_type=ct, object_id=assignment.id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_subject_alter_submission_status'),
        ('tags', '0001_initial'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        # Seed tags first (subject column still exists at this point), then drop it.
        migrations.RunPython(seed_subject_tags, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='assignment',
            name='subject',
        ),
    ]
