# Generated by Django 5.0.3 on 2025-04-14 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the assignment.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the assignment.', max_length=1000)),
                ('max_score', models.PositiveIntegerField(help_text='Maximum score that can be achieved for this assignment.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(help_text='The deadline for the homework.')),
                ('marked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('answer_text', models.TextField(blank=True, help_text="Student's written response.")),
                ('graded', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text="Teacher's feedback text.", max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the resource.', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the resource.', max_length=500, null=True)),
                ('file', models.FileField(blank=True, help_text='Upload a file for the resource.', null=True, upload_to='resources/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
