# Generated by Django 5.0.3 on 2024-08-22 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classes.event')),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('students', models.ManyToManyField(blank=True, related_name='class_events_as_student', to='user_accounts.customuser')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teachers', models.ManyToManyField(blank=True, related_name='class_events_as_teacher', to='user_accounts.customuser')),
            ],
            bases=('classes.event',),
        ),
    ]
