# Generated by Django 5.0.3 on 2024-11-23 10:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the assignment.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the assignment.', max_length=1000)),
                ('max_score', models.PositiveIntegerField(help_text='Maximum score that can be achieved for this assignment.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(help_text='The deadline for the homework.')),
                ('marked', models.BooleanField(default=False)),
                ('students', models.ManyToManyField(help_text='Students assigned to this work.', related_name='assignments_as_student', to='user_accounts.student')),
                ('subject', models.ForeignKey(help_text='The subject to which this assignment belongs.', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teachers', models.ManyToManyField(help_text='Teachers assigning this work.', related_name='assignments_as_teacher', to='user_accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classes.event')),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField(help_text='Duration of the class in minutes.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)])),
                ('students', models.ManyToManyField(blank=True, related_name='class_events_as_student', to='user_accounts.customuser')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teachers', models.ManyToManyField(blank=True, related_name='class_events_as_teacher', to='user_accounts.customuser')),
            ],
            bases=('classes.event',),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text="Teacher's feedback text.", max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.SmallIntegerField(null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='classes.assignment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the resource.', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the resource.', max_length=500, null=True)),
                ('file', models.FileField(blank=True, help_text='Upload a file for the resource.', null=True, upload_to='resources/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(help_text='The subject to which this resource belongs.', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('class_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='classes.classevent')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='material',
            field=models.ManyToManyField(related_name='homework_resource', to='classes.teachingresource'),
        ),
    ]
