# Generated by Django 5.0.3 on 2024-09-03 15:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='teachers',
            field=models.ManyToManyField(help_text='Teachers assigning this work.', related_name='assignments_as_teacher', to='user_accounts.customuser'),
        ),
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classes.event')),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField(help_text='Duration of the class in minutes.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)])),
                ('students', models.ManyToManyField(blank=True, related_name='class_events_as_student', to='user_accounts.customuser')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teachers', models.ManyToManyField(blank=True, related_name='class_events_as_teacher', to='user_accounts.customuser')),
            ],
            bases=('classes.event',),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='subject',
            field=models.ForeignKey(help_text='The subject to which this resource belongs.', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='homework',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='homework_assignments', to='user_accounts.customuser'),
        ),
        migrations.AddField(
            model_name='homework',
            name='class_event',
            field=models.ForeignKey(help_text='The class event associated with this homework.', on_delete=django.db.models.deletion.CASCADE, to='classes.classevent'),
        ),
    ]
