# Generated by Django 5.0.3 on 2025-04-14 22:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(help_text='Students assigned to this work.', related_name='assignments_as_student', to='user_accounts.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(help_text='The subject to which this assignment belongs.', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teachers',
            field=models.ManyToManyField(help_text='Teachers assigning this work.', related_name='assignments_as_teacher', to='user_accounts.customuser'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='classes.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_attempts', to='user_accounts.student'),
        ),
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classes.event')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField(help_text='Duration of the class in minutes.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)])),
                ('students', models.ManyToManyField(blank=True, related_name='class_events_as_student', to='user_accounts.customuser')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teachers', models.ManyToManyField(blank=True, related_name='class_events_as_teacher', to='user_accounts.customuser')),
            ],
            bases=('classes.event',),
        ),
        migrations.AddField(
            model_name='feedback',
            name='assignmentAttempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='classes.assignmentattempt'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.customuser'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='subject',
            field=models.ForeignKey(help_text='The subject to which this resource belongs.', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='assignmentattempt',
            name='submitted_files',
            field=models.ManyToManyField(blank=True, related_name='assignment_attempts', to='classes.teachingresource'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='material',
            field=models.ManyToManyField(related_name='homework_resource', to='classes.teachingresource'),
        ),
        migrations.AddField(
            model_name='teachingresource',
            name='class_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='classes.classevent'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentattempt',
            unique_together={('assignment', 'student')},
        ),
    ]
