# Generated by Django 5.0.3 on 2024-11-23 10:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(help_text='The deadline for the homework.', validators=[django.core.validators.MinValueValidator(datetime.date(2024, 11, 23))]),
        ),
    ]
