# Generated by Django 5.0.3 on 2024-08-22 22:12

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the assignment.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the assignment.', max_length=1000)),
                ('max_score', models.PositiveIntegerField(help_text='Maximum score that can be achieved for this assignment.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(help_text='The subject to which this assignment belongs.', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teachers', models.ManyToManyField(help_text='Teachers assigning this work.', related_name='assignments_as_teacher', to='user_accounts.customuser')),
            ],
        ),
        migrations.AlterField(
            model_name='classevent',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='Duration of the class in minutes.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.CreateModel(
            name='TeachingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the resource.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the resource.', max_length=500)),
                ('file', models.FileField(blank=True, help_text='Upload a file for the resource.', null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True, help_text='URL to an online resource.', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(help_text='The subject to which this resource belongs.', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('assignment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classes.assignment')),
                ('due_date', models.DateTimeField(help_text='The deadline for the homework.', validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 8, 22, 22, 12, 54, 95943, tzinfo=datetime.timezone.utc))])),
                ('submission_instructions', models.TextField(blank=True, help_text='Instructions on how to submit the homework.', max_length=1000)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Indicates if the homework is mandatory.')),
                ('assigned_students', models.ManyToManyField(blank=True, related_name='homework_assignments', to='user_accounts.customuser')),
                ('class_event', models.ForeignKey(help_text='The class event associated with this homework.', on_delete=django.db.models.deletion.CASCADE, to='classes.classevent')),
            ],
            bases=('classes.assignment',),
        ),
    ]
