# Generated by Django 5.0.3 on 2024-08-23 17:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_assignment_alter_classevent_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(help_text='The deadline for the homework.', validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 8, 23, 17, 19, 37, 458071, tzinfo=datetime.timezone.utc))]),
        ),
    ]
