# Generated by Django 5.0.3 on 2025-04-18 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='set_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date when the homework was assigned.'),
        ),
    ]
