# Generated by Django 5.0.3 on 2024-09-03 15:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(help_text='The deadline for the homework.', validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 9, 3, 15, 25, 15, 783482, tzinfo=datetime.timezone.utc))]),
        ),
    ]
