# Generated by Django 5.0.3 on 2025-02-24 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classevent',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2025, 2, 24, 23, 22, 49, 576367, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
