# Generated by Django 5.0.3 on 2025-01-04 15:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(help_text='The deadline for the homework.', validators=[django.core.validators.MinValueValidator(datetime.date(2025, 1, 4))]),
        ),
    ]
