# Generated by Django 5.0.3 on 2025-05-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the assignment.', max_length=1000, null=True),
        ),
    ]
