# Generated by Django 5.0.3 on 2025-05-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_assignment_description'),
        ('classes', '0003_assignment_set_date'),
    ]

    operations = [
    ]
