# Generated by Django 5.0.3 on 2025-02-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classevent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classevent',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
