# Generated by Django 5.0.3 on 2025-05-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_merge_20250501_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='to_mark',
            field=models.BooleanField(default=False),
        ),
    ]
