# Generated by Django 5.0.3 on 2025-04-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_classevent_created_at'),
        ('user_accounts', '0002_classgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='assignment',
        ),
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('answer_text', models.TextField(blank=True, help_text="Student's written response.")),
                ('graded', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='classes.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_attempts', to='user_accounts.student')),
                ('submitted_files', models.ManyToManyField(blank=True, related_name='assignment_attempts', to='classes.teachingresource')),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='assignmentAttempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='classes.assignmentattempt'),
        ),
    ]
