# Generated by Django 5.0.3 on 2025-05-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_assignment_to_mark'),
        ('user_accounts', '0002_remove_teacher_subjects_customaccount_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='class_groups',
            field=models.ManyToManyField(related_name='assignment_as_class_group', to='user_accounts.classgroup'),
        ),
    ]
