# Generated by Django 5.0.3 on 2024-09-10 22:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_homework_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingresource',
            name='url',
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(help_text='The deadline for the homework.', validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 9, 10, 22, 1, 43, 718420, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the resource.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='name',
            field=models.CharField(help_text='Name of the resource.', max_length=200, null=True),
        ),
    ]
