# Generated by Django 5.0.3 on 2024-09-11 22:05

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_remove_teachingresource_url_alter_homework_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingresource',
            name='class_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.classevent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(help_text='The deadline for the homework.', validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 9, 11, 22, 5, 3, 813165, tzinfo=datetime.timezone.utc))]),
        ),
    ]
