# Generated by Django 5.0.3 on 2024-09-12 20:25

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_teachingresource_class_event_alter_homework_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(help_text='The deadline for the homework.', validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 9, 12, 20, 25, 31, 671381, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='class_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='classes.classevent'),
        ),
    ]
