# Generated by Django 5.0.3 on 2024-10-27 12:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_alter_homework_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(help_text='The deadline for the homework.', validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 10, 27, 12, 32, 57, 515030, tzinfo=datetime.timezone.utc))]),
        ),
    ]
