# Generated by Django 5.0.3 on 2024-11-11 23:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_alter_homework_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(help_text='The deadline for the homework.', validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 11, 11, 23, 42, 58, 291711, tzinfo=datetime.timezone.utc))]),
        ),
    ]
