"""
Django settings for lessonbase project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = os.environ.get('ENVIRONMENT') == 'development'

BASE_URL = os.environ.get('BASE_URL')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

HOSTNAME = os.environ.get('HOSTNAME')

# Allow configuring ALLOWED_HOSTS via environment variable (comma-separated)
# Example: ALLOWED_HOSTS=backend-late-haze-5388.fly.dev,mydomain.com
env_allowed = os.environ.get('ALLOWED_HOSTS')
ALLOWED_HOSTS = [
    HOSTNAME,
    'localhost',
    '127.0.0.1',
]
if env_allowed:
    # Merge additional hosts from env (strip whitespace, ignore empties)
    ALLOWED_HOSTS += [h.strip() for h in env_allowed.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'rest_framework.authtoken',
    'polymorphic',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    'apps.subjects',
    'apps.user_accounts',  
    'apps.classes',
    'apps.storage',
    'apps.assignments',
    'backend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CORS middleware must come before CommonMiddleware so it can intercept
    # and respond to preflight OPTIONS requests.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lessonbase.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lessonbase.wsgi.application'
ASGI_APPLICATION = 'lessonbase.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Encoded credentials (this step ensures any special characters in the password are correctly parsed)
MONGO_USERNAME = os.environ.get('MONGO_USERNAME')
MONGO_PASSWORD = os.environ.get('MONGO_PASSWORD')

# Full MongoDB connection string
MONGO_URI = f"mongodb+srv://{MONGO_USERNAME}:{MONGO_PASSWORD}@cluster0.vihugpn.mongodb.net/?retryWrites=true&w=majority&authSource=admin"



# If using pymongo with a custom storage backend
MONGO_HOST = f"mongodb+srv://{MONGO_USERNAME}:{MONGO_PASSWORD}@cluster0.vihugpn.mongodb.net"
MONGO_DB_NAME = str(os.environ.get('MONGO_DB_NAME'))
MONGO_PORT = str(os.environ.get('MONGO_PORT'))

# Use the custom GridFS storage backend for file storage
DEFAULT_FILE_STORAGE = 'apps.storage.storage_backends.GridFSStorage'
GRIDFS_COLLECTION = 'files'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")


if DATABASE_URL:
    # ✅ Production or any environment using DATABASE_URL
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
        )
    }
else:
    # ✅ Development using local Postgres environment variables
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'mydb'),
            'USER': os.environ.get('POSTGRES_USER', 'myuser'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'mypassword'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ]
}




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_USER_MODEL = 'user_accounts.CustomAccount'

# CORS configuration. In production we recommend setting this via an
# environment variable containing a comma-separated list of origins
# (for example: CORS_ALLOWED_ORIGINS=https://your-frontend.vercel.app)
default_cors = [
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "https://lessonbase-rhbiibpgq-james-projects-0676d781.vercel.app",
    "https://lessonbase.vercel.app/"
]
cors_env = os.environ.get('CORS_ALLOWED_ORIGINS')
if cors_env:
    # Allow passing a comma-separated list in the environment
    CORS_ALLOWED_ORIGINS = [o.strip() for o in cors_env.split(',') if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = default_cors

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jamespeterkenny@gmail.com'  # Enter your Gmail email address
EMAIL_HOST_PASSWORD = 'vxxd sduk srbp tdxv'  # Enter your Gmail password

