# Generated by Django 5.0.3 on 2025-05-13 19:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0002_subject_code_alter_subject_color'),
        ('user_accounts', '0002_remove_teacher_subjects_customaccount_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the assignment.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the assignment.', max_length=1000, null=True)),
                ('max_score', models.PositiveIntegerField(help_text='Maximum score that can be achieved for this assignment.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_date', models.DateField(default=django.utils.timezone.now, help_text='The date when the homework was assigned.')),
                ('due_date', models.DateField(help_text='The deadline for the homework.')),
                ('to_mark', models.BooleanField(default=False)),
                ('marked', models.BooleanField(default=False)),
                ('class_groups', models.ManyToManyField(related_name='assignment_as_class_group', to='user_accounts.classgroup')),
                ('material', models.ManyToManyField(related_name='homework_resource', to='classes.teachingresource')),
                ('students', models.ManyToManyField(help_text='Students assigned to this work.', related_name='assignments_as_student', to='user_accounts.student')),
                ('subject', models.ForeignKey(help_text='The subject to which this assignment belongs.', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teachers', models.ManyToManyField(help_text='Teachers assigning this work.', related_name='assignments_as_teacher', to='user_accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('answer_text', models.TextField(blank=True, help_text="Student's written response.")),
                ('graded', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_attempts', to='user_accounts.student')),
                ('submitted_files', models.ManyToManyField(blank=True, related_name='assignment_attempts', to='classes.teachingresource')),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text="Teacher's feedback text.", max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.SmallIntegerField(null=True)),
                ('assignmentAttempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='assignments.assignmentattempt')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.customuser')),
            ],
        ),
    ]
