# Generated by Django 5.2.5 on 2025-11-03 15:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('password_reset_token', models.UUIDField(default=uuid.uuid4, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomAccount',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_accounts.customuser')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('premium_account', models.BooleanField(default=False)),
                ('confirmation_token', models.UUIDField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('subjects', models.ManyToManyField(to='subjects.subject')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('user_accounts.customuser', models.Model),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staff_user', serialize=False, to='user_accounts.customuser')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('user_accounts.customaccount',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('customaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hire_date', models.DateField(null=True)),
                ('students', models.ManyToManyField(to='user_accounts.student')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('user_accounts.customaccount',),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('class_code', models.CharField(max_length=50, unique=True)),
                ('max_students', models.PositiveIntegerField(blank=True, null=True)),
                ('symbol', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('archived', 'Archived')], default='active', max_length=10)),
                ('color', models.CharField(choices=[('#1976D2', 'Blue'), ('#388E3C', 'Green'), ('#7B1FA2', 'Purple'), ('#D32F2F', 'Red'), ('#F57C00', 'Orange'), ('#0097A7', 'Cyan'), ('#C2185B', 'Pink'), ('#5D4037', 'Brown'), ('#455A64', 'Blue Grey'), ('#FBC02D', 'Yellow')], default='#1976D2', max_length=7)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_class_groups', to='user_accounts.customuser')),
                ('subjects', models.ManyToManyField(related_name='class_groups', to='subjects.subject')),
                ('students', models.ManyToManyField(related_name='class_groups', to='user_accounts.student')),
                ('teachers', models.ManyToManyField(related_name='class_groups', to='user_accounts.teacher')),
            ],
        ),
    ]
