# Generated by Django 5.2.5 on 2026-06-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_classgroup_class_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_updates', models.BooleanField(default=False)),
                ('tips_and_tutorials', models.BooleanField(default=False)),
                ('promotions', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'marketing preferences',
            },
        ),
    ]
