# Generated by Django 5.0.3 on 2024-08-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classevent',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='classevent',
            name='students',
        ),
        migrations.RemoveField(
            model_name='classevent',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='classevent',
            name='teachers',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='ClassEvent',
        ),
    ]
