# Generated by Django 5.0.3 on 2024-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='confirmation_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
