# Generated by Django 5.0.3 on 2024-05-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='penis', max_length=100),
            preserve_default=False,
        ),
    ]
