# Generated by Django 5.0.3 on 2024-04-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraccount',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'base_manager_name': 'objects'},
        ),
    ]
