# Generated by Django 5.0.3 on 2024-04-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_customeraccount_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(to='backend.student'),
        ),
    ]
