# Generated by Django 5.0.3 on 2024-06-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='profile_picture_url',
            field=models.URLField(null=True),
        ),
    ]
