# Generated by Django 5.0.3 on 2024-06-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_customeraccount_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='name',
            field=models.CharField(default='default name'),
        ),
    ]
