# Generated by Django 5.0.3 on 2024-04-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_teacher_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(to='backend.student'),
        ),
    ]
