# Generated by Django 5.0.3 on 2024-06-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_customeraccount_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='name',
        ),
    ]
