# Generated by Django 5.0.3 on 2024-06-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_customeraccount_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
