# Generated by Django 5.0.3 on 2024-04-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_teacher_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(null=True, to='backend.subject'),
        ),
    ]
